---
all:
  hosts:
    << vm_hostname >>:
      ansible_host: << ansible_host >>
      ansible_user: << ansible_user >>
      ansible_port: << ansible_port >>
      ansible_ssh_private_key_file: << ansible_ssh_private_key_file >>
